extract = 'total_dyn_inst: (\d+)'
benchmarks = './tests/*.bril'

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

[runs.opt]
pipeline = [
    "bril2json",
    "./lvn_exec",
    "./dve_exec",
    "brili {args}",
]
