benchmarks = "./core/*.bril"

extract = 'total_dyn_inst:\s*(\d+)'

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p"
]

[runs.opt]
pipeline = [
    "bril2json",
    "./lvn_exec",
    "./dce_exec",
    "brili -p"
]
